# Generated by Django 5.2.7 on 2025-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_coupon_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=200, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=255, verbose_name="postal_code"),
        ),
    ]
